### ISSUE TITLE
VGG Perceptual loss vs WatsonDistance loss

### ISSUE THREAD

**Issue by phongnhhn92** [SteffenCzolbe/PerceptualSimilarity#11]
Hello,
Thanks for your code! I think this is very impressive work. I am working on the problem of image-to-image translation and I would like to try your proposed loss function. I wonder how much performance gain can I have if I used your Watson loss function.

Another question is: I found in your code there are 3 kinds of Watson losses: [WatsonDistanceDCT](https://github.com/phongnhhn92/PerceptualSimilarity/blob/727781cddebffeace979ccd32e2667e6cc566850/src/loss/watson.py#L13), [WatsonDistanceFft](https://github.com/phongnhhn92/PerceptualSimilarity/blob/727781cddebffeace979ccd32e2667e6cc566850/src/loss/watson_fft.py#L13) and [WatsonDistanceVgg](https://github.com/phongnhhn92/PerceptualSimilarity/blob/727781cddebffeace979ccd32e2667e6cc566850/src/loss/watson_vgg.py#L63).

I understand that WatsonDistanceFft is better than WatsonDistanceDCT but how about WatsonDistanceVgg. I read your paper and it seems like FFT is a very important part to make your loss better then L1,L2 and adaptive Loss. However, when I check the code, I dont see you perform any FFT on extracted VGG features.

Sorry for a lot of questions but I really hope to apply your method on my problem.

**Comment by SteffenCzolbe** [comment]
WatsonDistanceFft is the Watson-DFT evaluated in the paper. The other two were evaluated in development, but ultimately didn't make the cut for the final version.
