### ISSUE TITLE
minimum loss function value

### ISSUE THREAD

**Issue by artyomnaz** [SteffenCzolbe/PerceptualSimilarity#14]
Hello!
Thanks for your work!
I would like to ask you why loss function value for the same inputs is not equal zero? What are the reasons of this behavior?
![image](https://user-images.githubusercontent.com/47011391/109470896-106ed180-7a81-11eb-8629-d168eb5b9764.png)

**Comment by denadai2** [comment]
I am interested as well

**Comment by ucalyptus2** [comment]
@SteffenCzolbe

**Comment by SteffenCzolbe** [comment]
Sorry for missing this issue earlier.

To make the function fully differentiable, even in the extreme ranges if the input, we had to add small constants in multiple places. The constants sadly make the minimum slightly greater than 0.

See all the EPS values here:
https://github.com/SteffenCzolbe/PerceptualSimilarity/blob/3729dd1fc7e7082c0c66f7dc74d119a78948cb17/src/loss/watson_fft.py#L85-L110
